org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.configuration-cache=true

plugin_version=0.0.1
paper_version=26.2.build.65-beta
craft_engine_version=26.8.1
craft_engine_proxy_version=26.8.1
custom_crops_version=3.6.52
placeholder_api_version=2.11.6
sparrow_yaml_version=1.0.7
